# Generated by Django 4.1.7 on 2023-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_aluno_opcao_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='aluno',
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.aluno')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.opcao')),
            ],
            options={
                'unique_together': {('aluno', 'opcao')},
            },
        ),
        migrations.AddField(
            model_name='opcao',
            name='alunos',
            field=models.ManyToManyField(through='votacao.Voto', to='votacao.aluno'),
        ),
    ]
